// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjmXv0dEirqLJeqTjbqting4Dq1EdBMsA',
    appId: '1:958418232564:web:9a2121a4cd371b0bbeeaa1',
    messagingSenderId: '958418232564',
    projectId: 'myhomeaccess-365ff',
    authDomain: 'myhomeaccess-365ff.firebaseapp.com',
    storageBucket: 'myhomeaccess-365ff.appspot.com',
    measurementId: 'G-WFRQZH7W7N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJ29bflQkMDc3grTJpasBVvusvgfyiUy4',
    appId: '1:958418232564:android:3616c4bfa3b562aabeeaa1',
    messagingSenderId: '958418232564',
    projectId: 'myhomeaccess-365ff',
    storageBucket: 'myhomeaccess-365ff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcjCF-iB8Th2NXdQvVygngytls3N0t1bA',
    appId: '1:958418232564:ios:2f72bd4aa7909fd1beeaa1',
    messagingSenderId: '958418232564',
    projectId: 'myhomeaccess-365ff',
    storageBucket: 'myhomeaccess-365ff.appspot.com',
    iosBundleId: 'com.example.myhomeAccess',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcjCF-iB8Th2NXdQvVygngytls3N0t1bA',
    appId: '1:958418232564:ios:8e86c97308deda49beeaa1',
    messagingSenderId: '958418232564',
    projectId: 'myhomeaccess-365ff',
    storageBucket: 'myhomeaccess-365ff.appspot.com',
    iosBundleId: 'com.example.myhomeAccess.RunnerTests',
  );
}
